name: Use Docker CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        artifact:
          - name: frontend
            context: './frontend'
            dockerfile: './frontend/Dockerfile'
            repository: 'rajsomesetty/multiartifact-frontend'
            image_tag: "frontend-${{ github.run_id }}"
          - name: backend
            context: './backend'
            dockerfile: './backend/Dockerfile'
            repository: 'rajsomesetty/multiartifact-backend'
            image_tag: "backend-${{ github.run_id }}"
    uses: girichinna27/reusable-workflows/.github/workflows/docker-image.yml@main
    with:
      image_tag: ${{ matrix.artifact.image_tag }}
      registry: 'docker.io'
      repository: ${{ matrix.artifact.repository }}
      dockerfile: ${{ matrix.artifact.dockerfile }}
      context: ${{ matrix.artifact.context }}
      rabbitmq_url: "http://34.29.129.115:15672"
      rabbitmq_queue: "githubactions-ssd"
      rabbitmq_exchange: "githubactions.events"
      rabbitmq_binding_key: "githubactions-ssd"
      org: "ortseam"
      application_tags: "v1.0"
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      rabbitmq_user: ${{ secrets.RABBITMQ_USER }}
      rabbitmq_pass: ${{ secrets.RABBITMQ_PASS }}
